// app/layout.tsx
import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "./components/Footer";
import Header from "./components/Header";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

/* ---------- SEO: Viewport ---------- */
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#0b0f1a",
  colorScheme: "dark",
};

/* ---------- Massive SEO Keywords: English + Hindi ---------- */
const seoKeywords = [
  "VeyoScan",
  "Veyo Scan",
  "veyoscan",
  "veyoscan.com",
  "VeyoScan India",
  "VeyoScan QR",
  "VeyoScan smart QR solution",
  "VeyoScan digital QR platform",
  "VeyoScan customer connect solution",
  "VeyoScan business QR services",
  "QR code solution",
  "QR code platform",
  "smart QR code",
  "dynamic QR code",
  "intelligent QR code",
  "business QR code",
  "custom QR code",
  "secure QR code",
  "scan to connect",
  "scan to call",
  "scan to chat",
  "scan to message",
  "scan to contact",
  "scan to support",
  "scan to WhatsApp",
  "scan to website",
  "scan to feedback",
  "scan to complaint",
  "scan to enquiry",
  "QR communication platform",
  "QR customer engagement",
  "QR business communication",
  "QR lead generation",
  "QR code for business",
  "QR code for marketing",
  "QR code for support",
  "QR code customer care",
  "QR code customer service",
  "QR code helpline",
  "QR code call system",
  "QR based contact solution",
  "QR based support solution",
  "QR code for brands",
  "QR code tracking",
  "QR code analytics",
  "bulk QR management",
  "QR code dashboard",
  "QR code SaaS",
  "enterprise QR solution",
  "digital QR platform",
  "cloud QR platform",
  "business scan solution",
  "scan and connect instantly",
  "no app QR solution",
  "QR code automation",
  "smart business QR",
  "customer experience QR",
  "direct connect QR",
  "real time QR connect",
  "owner verified QR",
  "QR code with analytics",
  "multi use QR code",
  "editable QR code",
  "trackable QR code",
  "QR call solution India",
  "best QR solution in India",
  "QR platform India",
  "QR tech company India",
  "startup QR solution",
  "advanced QR system",
  "smart scan technology",
  "business growth QR solution",
  "digital contact QR",
  "paperless QR solution",
  "fast connect QR system",
  "smart customer support QR",
  "instant customer connect solution",
  "vehicle QR code",
  "car QR code",
  "bike QR code",
  "parking QR code",
  "wrong parking QR code",
  "shop QR code",
  "business card QR",
  "personal QR code",
  "house QR code",
  "society QR code",
  "office QR code",
  "apartment QR code",
  "store QR code",
  "restaurant QR code",
  "hotel QR code",
  "school QR code",
  "college QR code",
  "hospital QR code",
  "clinic QR code",
  "pharmacy QR code",
  "warehouse QR code",
  "factory QR code",
  "retail QR code",
  "event QR code",
  "delivery QR code",
  "product QR code",
  "packaging QR code",
  "asset tracking QR",
  "service request QR",
  "complaint management QR",
  "feedback QR for business",
  "customer review QR",
  "table QR code",
  "menu QR code",
  "bill payment QR display",
  "QR for startups",
  "QR for enterprises",
  "QR for local business",
  "QR for vendors",
  "QR for real estate",
  "QR for transport",
  "QR for logistics",
  "QR for ecommerce",
  "QR for manufacturers",
  "QR for dealers",
  "QR for distributors",
  "QR for field service",
  "QR for maintenance",
  "QR for visitors",
  "QR for gate entry",
  "QR for security",
  "QR for emergency contact",
  "scan to call business",
  "QR call now",
  "QR direct call",
  "QR voice support",
  "QR phone connect",
  "scan for instant support",
  "scan for customer care",
  "scan for contact details",
  "scan for quick response",
  "QR to WhatsApp chat",
  "QR to live support",
  "scan to connect owner",
  "scan to contact seller",
  "scan to contact driver",
  "scan to contact resident",
  "scan to connect business owner",
  "instant scan support",
  "clickless contact solution",
  "one scan one connect",
  "QR marketing solution",
  "QR code branding",
  "QR campaign solution",
  "digital engagement QR",
  "QR performance tracking",
  "QR scan analytics",
  "location based QR",
  "lead capture QR",
  "promo QR code",
  "smart ad QR",
  "print to digital QR",
  "offline to online QR",
  "QR conversion tracking",
  "customer funnel QR",
  "social media QR code",
  "QR for Facebook",
  "QR for Instagram",
  "QR for YouTube",
  "website traffic from QR",
  "QR for advertising",
  "QR for promotions",
  "QR for retail marketing",
  "QR solution for local marketing",
  "brand promotion using QR",
  "QR code solution India hindi",
  "business ke liye QR code",
  "scan karke call kare",
  "scan karke connect kare",
  "scan karke chat kare",
  "scan karke support paye",
  "QR code se customer connect",
  "QR code se call",
  "QR code se WhatsApp chat",
  "QR code se enquiry",
  "QR code se complaint",
  "QR code se feedback",
  "QR code se owner se baat kare",
  "vehicle ke liye QR code",
  "shop ke liye QR code",
  "ghar ke liye QR code",
  "business QR solution india",
  "smart QR platform",
  "dynamic QR code india",
  "best QR code service",
  "QR code marketing solution",
  "QR code tracking system",
  "QR code analytics platform",
  "customer engagement QR code",
  "scan to call hindi",
  "scan to connect hindi",
  "scan to support hindi",
  "QR se direct baat kare",
  "QR se call kare",
  "QR se contact kare",
  "QR se jankari paaye",
  "QR se enquiry bheje",
  "QR se feedback de",
  "QR se complaint kare",
  "QR customer support india",
  "smart business solution india",
  "qr code company india",
  "digital business solution",
  "business growth ke liye qr code",
  "qr code se lead generate kare",
  "qr code se business badhaye",
  "qr code se customers tak pahuche",
  "qr code se support system",
  "qr based communication platform",
  "modern qr code solution",
  "क्यूआर कोड समाधान",
  "क्यूआर कोड प्लेटफॉर्म",
  "स्मार्ट क्यूआर कोड",
  "डायनेमिक क्यूआर कोड",
  "बिजनेस क्यूआर कोड",
  "कस्टम क्यूआर कोड",
  "सुरक्षित क्यूआर कोड",
  "स्कैन टू कॉल",
  "स्कैन टू चैट",
  "स्कैन टू कनेक्ट",
  "स्कैन करके संपर्क करें",
  "स्कैन करके कॉल करें",
  "स्कैन करके चैट करें",
  "स्कैन करके सपोर्ट पाएं",
  "क्यूआर कोड से ग्राहक जुड़ें",
  "क्यूआर कोड से कॉल करें",
  "क्यूआर कोड से व्हाट्सएप चैट",
  "क्यूआर कोड से फीडबैक",
  "क्यूआर कोड से शिकायत",
  "क्यूआर कोड से पूछताछ",
  "क्यूआर कोड से बिजनेस ग्रोथ",
  "व्यवसाय के लिए क्यूआर कोड",
  "दुकान के लिए क्यूआर कोड",
  "वाहन के लिए क्यूआर कोड",
  "घर के लिए क्यूआर कोड",
  "सोसायटी के लिए क्यूआर कोड",
  "ऑफिस के लिए क्यूआर कोड",
  "रेस्टोरेंट के लिए क्यूआर कोड",
  "होटल के लिए क्यूआर कोड",
  "स्कूल के लिए क्यूआर कोड",
  "अस्पताल के लिए क्यूआर कोड",
  "ग्राहक सेवा क्यूआर कोड",
  "कस्टमर सपोर्ट क्यूआर कोड",
  "व्यापारिक क्यूआर समाधान",
  "भारत में क्यूआर कोड सेवा",
  "भारत का स्मार्ट क्यूआर प्लेटफॉर्म",
  "क्यूआर कोड एनालिटिक्स",
  "क्यूआर कोड ट्रैकिंग",
  "क्यूआर कोड मार्केटिंग",
  "क्यूआर कोड प्रमोशन",
  "क्यूआर कोड अभियान",
  "डिजिटल कनेक्ट समाधान",
  "तुरंत संपर्क समाधान",
  "बिना ऐप के क्यूआर समाधान",
  "रीयल टाइम क्यूआर कनेक्ट",
  "क्यूआर आधारित ग्राहक जुड़ाव",
  "क्यूआर आधारित संचार प्लेटफॉर्म",
  "क्यूआर से सीधे मालिक से बात करें",
  "क्यूआर कोड से तुरंत सहायता",
  "क्यूआर कोड से ग्राहक प्रतिक्रिया",
  "क्यूआर कोड से शिकायत प्रबंधन",
  "क्यूआर कोड से लीड जनरेशन",
  "क्यूआर कोड से ब्रांड प्रमोशन",
  "क्यूआर कोड से वेबसाइट विजिट",
  "क्यूआर कोड से सोशल मीडिया",
  "क्यूआर कोड से फेसबुक",
  "क्यूआर कोड से इंस्टाग्राम",
  "क्यूआर कोड से यूट्यूब",
  "क्यूआर टेक्नोलॉजी इंडिया",
  "भारत में सर्वश्रेष्ठ क्यूआर कोड समाधान",
  "वेयोस्कैन",
  "वेयो स्कैन",
  "वेयोस्कैन डॉट कॉम",
  "वेयोस्कैन क्यूआर सेवा",
  "वेयोस्कैन स्मार्ट क्यूआर प्लेटफॉर्म",
  "best dynamic QR code platform for business in India",
  "smart QR code solution for shops and businesses",
  "scan to call QR code service provider in India",
  "QR code based customer support system for business",
  "best QR communication platform for Indian businesses",
  "dynamic QR code with analytics and dashboard",
  "business QR code with customer engagement tools",
  "custom QR code platform for brands and startups",
  "QR code for instant customer support and contact",
  "smart QR code solution for vehicle and parking",
  "QR code for shop marketing and customer connection",
  "QR code solution for restaurants hotels and clinics",
  "QR code with social media integration for business",
  "QR code software for customer communication",
  "enterprise grade QR code platform India",
  "digital business card QR solution",
  "scan to connect platform for local businesses",
  "best QR code service for Hindi and English users",
  "भारतीय व्यवसायों के लिए स्मार्ट क्यूआर कोड समाधान",
  "ग्राहक सहायता के लिए क्यूआर कोड प्लेटफॉर्म",
  "दुकानों और व्यवसायों के लिए डायनेमिक क्यूआर कोड",
  "स्कैन करके तुरंत कॉल और चैट समाधान",
  "वाहन और पार्किंग के लिए क्यूआर कोड समाधान",
  "सोशल मीडिया लिंक के साथ क्यूआर कोड प्लेटफॉर्म",
  "फीडबैक और शिकायत के लिए क्यूआर कोड सिस्टम",
  "veyoscan qr code service",
  "veyoscan scan to call",
  "veyoscan scan to chat",
  "veyoscan customer connect",
  "veyoscan business connect",
  "veyoscan smart support",
  "veyoscan qr marketing",
  "veyoscan qr tracking",
  "veyoscan qr analytics",
  "veyoscan digital growth",
  "veyoscan startup solution",
  "veyoscan for shops",
  "veyoscan for vehicles",
  "veyoscan for homes",
  "veyoscan for offices",
  "veyoscan support qr",
  "veyoscan complaint qr",
  "veyoscan feedback qr",
  "veyoscan social qr",
  "veyoscan lead generation",
  "veyoscan secure qr",
  "veyoscan dynamic qr",
  "veyoscan bulk qr",
  "veyoscan enterprise qr",
  "veyoscan business solution India",
  "veyoscan Hindi English SEO",
  "veyoscan brand visibility",
  "veyoscan customer engagement",
  "veyoscan qr dashboard",
  "veyoscan smart code",
  "veyoscan qr technology",
  "veyoscan communication platform",
  "veyoscan qr for support",
  "veyoscan qr for enquiry",
  "veyoscan qr for complaints",
  "veyoscan qr for feedback",
  "veyoscan qr for customer service",
  "veyoscan qr for marketing campaigns",
  "veyoscan qr for growth",
  "veyoscan digital platform",
  "veyoscan online business tool",
  "veyoscan offline to online solution",
  "veyoscan smart contact system",
  "veyoscan instant communication",
  "veyoscan real time customer connect",
  "veyoscan modern QR solution",
  "veyoscan made for India",
  "veyoscan innovative QR platform",
  "veyoscan digital scan platform",
  "veyoscan qr code India",
  "veyoscan branded QR solution",
];

/* ---------- SEO Metadata ---------- */
export const metadata: Metadata = {
  metadataBase: new URL("https://veyoscan.com"),
  title: {
    default: "VeyoScan — Scan • Connect • Instantly | स्मार्ट QR कोड समाधान",
    template: "%s | VeyoScan",
  },
  description:
    "VeyoScan is a smart QR code platform that helps users scan to call, chat, connect, enquire, give feedback, and reach businesses instantly. VeyoScan offers modern QR solutions for vehicles, shops, homes, offices, and businesses across India. वेयोस्कैन एक स्मार्ट QR कोड प्लेटफॉर्म है जिससे यूज़र स्कैन करके तुरंत कॉल, चैट, सपोर्ट, फीडबैक और संपर्क कर सकते हैं।",
  keywords: seoKeywords,
  applicationName: "VeyoScan",
  icons: {
    icon: [
      { url: "/favicon.ico" },
      { url: "/images/final logo  (2).png", type: "image/png" },
    ],
    apple: [{ url: "/images/final logo  (2).png", type: "image/png" }],
  },
  manifest: "/site.webmanifest",
  alternates: {
    canonical: "https://veyoscan.com/",
    languages: {
      "en-IN": "https://veyoscan.com/",
      "hi-IN": "https://veyoscan.com/",
    },
  },
  openGraph: {
    type: "website",
    url: "https://veyoscan.com/",
    siteName: "VeyoScan",
    title: "VeyoScan — Smart QR Code Platform for Instant Connection",
    description:
      "Scan to call, scan to chat, scan to connect. VeyoScan helps businesses and users connect instantly through smart, secure, and trackable QR codes. स्कैन करें और तुरंत जुड़ें।",
    images: [
      {
        url: "/images/final logo  (2).png",
        width: 1200,
        height: 630,
        alt: "VeyoScan Logo",
      },
    ],
    locale: "en_IN",
  },
  twitter: {
    card: "summary_large_image",
    title: "VeyoScan — Scan • Connect • Instantly",
    description:
      "Smart QR code platform for call, chat, support, feedback, and customer engagement. हिंदी + English QR solution for India.",
    images: ["/images/logo.png"],
    creator: "@veyoscan",
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  category: "technology",
  creator: "VeyoScan",
  authors: [{ name: "VeyoScan" }],
  publisher: "VeyoScan",
};

/* ---------- Root Layout ---------- */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const orgJsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "VeyoScan",
    alternateName: ["Veyo Scan", "वेयोस्कैन"],
    url: "https://veyoscan.com/",
    logo: "https://veyoscan.com/images/logo.png",
    sameAs: [
      "https://www.facebook.com/profile.php?id=61572231007919",
      "https://www.instagram.com/veyoscan/",
      "https://www.youtube.com/@veyoscan",
    ],
    contactPoint: [
      {
        "@type": "ContactPoint",
        contactType: "Customer Support",
        areaServed: "IN",
        availableLanguage: ["en", "hi"],
      },
    ],
    description:
      "VeyoScan is a smart QR code technology platform helping users and businesses connect instantly through scan to call, scan to chat, scan to support, and smart QR engagement solutions in India.",
  };

  const siteSearchJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "VeyoScan",
    alternateName: "वेयोस्कैन",
    url: "https://veyoscan.com/",
    inLanguage: ["en-IN", "hi-IN"],
    potentialAction: {
      "@type": "SearchAction",
      target: "https://veyoscan.com/search?q={query}",
      "query-input": "required name=query",
    },
  };

  const webPageJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: "VeyoScan",
    url: "https://veyoscan.com/",
    description:
      "Smart QR code platform for businesses, vehicles, shops, homes, offices, support, and customer engagement in Hindi and English.",
    inLanguage: ["en-IN", "hi-IN"],
    isPartOf: {
      "@type": "WebSite",
      name: "VeyoScan",
      url: "https://veyoscan.com/",
    },
  };

  return (
  <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="antialiased bg-[#0b0f1a] text-white overflow-x-hidden">

        {/* ===== HEADER (FIXED) ===== */}
        <header className="fixed top-0 left-0 w-full z-50 h-16 md:h-20">
          <Header />
        </header>

        {/* ===== MAIN CONTENT (NO GAP ISSUE FIXED) ===== */}
        <main
          id="main-content"
          role="main"
          className="pt-16 md:pt-20" // ✅ mobile header 64px, desktop header 80px
        >
          {children}
        </main>

        {/* ===== FOOTER ===== */}
        <Footer />

        <Script
          id="ld-org"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(orgJsonLd) }}
        />
        <Script
          id="ld-site"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(siteSearchJsonLd) }}
        />
        <Script
          id="ld-webpage"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(webPageJsonLd) }}
        />
      </body>
    </html>
  );
}